### PR TITLE
Private fields

### LINKED ISSUE #14: Downlevel private fields
```ts
export declare class C {
  #private: string;
}
```

Proposed emit

```ts
declare const private: unique symbol;

export declare class C {
  private [private]: string
}
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #14 in a simple way.

### CODE REVIEW

**Comment by sandersn** [comment]
@DanielRosenwasser not sure when you'll have a chance to look at this, but you'll probably be interested.

@rbuckton and @robpalme I think you'll have opinions too.

**Comment by sandersn** [comment]
And @mheiber

**Comment by mheiber** [comment]
I like how this solution is really simple and the output is readable.

The only thing I can think of that seems strange is that it can produce declaration files that aren't valid ts (well, that wouldn't type-check):

```ts
declare class Parent {
    private "#private";
}

declare class Child extends Parent {
    private "#private";
}
```

This could be problematic for users that consumes declaratio files as TS. One use case for such a workflow is to do dead code elimination based on known entrypoints.

Is "valid .ts should produce .d.ts that is also valid .ts" a useful principle? I don't know the overall perspective on what declaration files can and can't do.

**Comment by sandersn** [comment]
I must be testing your example with stricter settings because I get an error both with the language service and tsc, in both d.ts and .ts. I think it needs to be mangled after all. I'll try `"Parent.#private"` and `"Child.#private"` respectively. 

At least, I didn't understand your point about dead code elimination. Are you suggesting that dead code elimination would avoid the need for mangling sometimes?

**Comment by mheiber** [comment]
Hi Nathan,

I'm now seeing the error as well: looks like I did the test wrong, glad you checked!

The dead code elimination thing I mentioned isn't important: it was an example of an obscure use case where it's nice to have valid .d.ts also be valid .ts.

**Comment by mheiber** [comment]
@sandersn , you wrote:

> I think it needs to be mangled after all. I'll try "Parent.#private" and "Child.#private" respectively.

Would including the Node ID (`"Parent.#private${node.id}"`) help to further reduce chance of conflict? The only downside I see would be that tests would be flaky if Node IDs vary a lot between TS versions.

**Comment by sandersn** [comment]
I don't think node ids are particularly stable, and I'm (right now at least) trying to make the common case work. So I think I'll wait until somebody files a bug.

I think the mostly likely source would be a series of classes that differ by containing namespace, but have the same name. It's possible that Azure SDK has this, so it might come up if they switch to private fields.

**Comment by mheiber** [comment]
:tada: thanks for the attention, this was an interesting question

**Pull request merged**
